.PHONY: clean All

All:
	@echo "----------Building project:[ Test_A - Debug ]----------"
	@cd "Test_A" && "$(MAKE)" -f  "Test_A.mk"
clean:
	@echo "----------Cleaning project:[ Test_A - Debug ]----------"
	@cd "Test_A" && "$(MAKE)" -f  "Test_A.mk" clean
